In [73]:
import numpy as np

import pandas as pd



In [2]:
l = ['krushna',1,2,3,4]

In [3]:
type(l)

list

In [5]:
np.array(l)

array(['krushna', '1', '2', '3', '4'], dtype='<U11')

In [7]:
type(np.array(l)) #nd means n-dimensional

numpy.ndarray

In [8]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [22]:
a1= np.array([3,4,5,6,7.0])

In [17]:
a = np.array([[1,2],[3,45]])

In [16]:
np.array([[1,2],[3,45,5]])

C:\Users\KRUSHNA\AppData\Local\Temp\ipykernel_964\1849100819.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2],[3,45,5]])


In [18]:
a

array([[ 1,  2],
       [ 3, 45]])

In [20]:
a[1][1]

45

In [21]:
a[1]

array([ 3, 45])

In [23]:
a1

array([3., 4., 5., 6., 7.])

In [24]:
a1[1]

4.0

In [27]:
np.array([1,2,3,4],ndmin = 0)

array([1, 2, 3, 4])

In [28]:
np.array([1,2,3,4],ndmin = 2)

array([[1, 2, 3, 4]])

In [33]:
a2 = np.array([1,2,3,4],ndmin = 3)

In [34]:
a2

array([[[1, 2, 3, 4]]])

In [32]:
a2[0]

array([[1, 2, 3, 4]])

In [38]:
a2[0][0]

array([1, 2, 3, 4])

In [39]:
a2[0][0][0]

1

In [40]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [41]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [42]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [43]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [44]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [45]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [46]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [52]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [53]:
np.fromfunction(lambda i,j : i*j,(4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [54]:
np.mat(np.fromfunction(lambda i,j : i*j,(4,4),dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

# NOTE : matrix is a subclass of array

In [57]:
np.fromfunction(lambda i,j,z : i*j*z,(3,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [58]:
np.mat(np.fromfunction(lambda i,j,z : i*j*z,(3,3,2),dtype = int)) # matrix doesn't shows three dimensional array

ValueError: shape too large to be a matrix.

In [59]:
np.fromfunction(lambda i,j,z : i*j*z,(5,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]],

       [[0, 0],
        [0, 4],
        [0, 8]]])

In [60]:
np.fromfunction(lambda i,j,z,p : i*j*z*p,(4,3,2,2),dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [62]:
a =np.fromfunction(lambda i,j,z,: i*j*z,(4,3,2),dtype = int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [63]:
a.ndim

3

In [69]:
a.size

24

In [67]:
a.shape

(4, 3, 2)

In [70]:
a.dtype

dtype('int32')

In [71]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [74]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [75]:
a1 =np.fromfunction(lambda i,j,: i*j,(4,3),dtype = int)
a1

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [76]:
pd.DataFrame(a1)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [81]:
a2 =np.fromfunction(lambda i,j,: i*j,(400,400),dtype = int)
a2

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    397,    398,    399],
       [     0,      2,      4, ...,    794,    796,    798],
       ...,
       [     0,    397,    794, ..., 157609, 158006, 158403],
       [     0,    398,    796, ..., 158006, 158404, 158802],
       [     0,    399,    798, ..., 158403, 158802, 159201]])

In [82]:
pd.DataFrame(a2)

0    1    2     3     4     5     6     7     8     9    ...     390  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     390   
2      0    2    4     6     8    10    12    14    16    18  ...     780   
3      0    3    6     9    12    15    18    21    24    27  ...    1170   
4      0    4    8    12    16    20    24    28    32    36  ...    1560   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  154050   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  154440   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  154830   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  155220   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  155610   

        391     392     393     394     395     396     397     398     399  
0         0       0       0       0       0       0       0       0       0  
1       391     392     393     394     395     396     397     398     399  
2       782     784     786     788     790     792     794     796     798  
3      1173    1176    1179    1182    1185    1188    1191    1194    1197  
4      1564    1568    1572    1576    1580    1584    1588    1592    1596  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  154445  154840  155235  155630  156025  156420  156815  157210  157605  
396  154836  155232  155628  156024  156420  156816  157212  157608  158004  
397  155227  155624  156021  156418  156815  157212  157609  158006  158403  
398  155618  156016  156414  156812  157210  157608  158006  158404  158802  
399  156009  156408  156807  157206  157605  158004  158403  158802  159201  

[400 rows x 400 columns]

In [83]:
np.random.rand(100,4)

array([[9.07739080e-01, 7.34805429e-01, 3.31414486e-01, 6.65374487e-01],
       [9.57437693e-01, 2.13560165e-02, 2.47621713e-01, 6.41756327e-01],
       [5.76863388e-02, 5.71621120e-01, 4.45411254e-01, 1.15848131e-01],
       [1.15289155e-01, 2.38094368e-01, 6.54363808e-01, 8.31406504e-01],
       [4.17651927e-01, 6.13165463e-02, 3.16155221e-01, 7.89616698e-01],
       [9.45514942e-01, 3.48334070e-02, 2.00032945e-01, 9.09164322e-01],
       [7.01591319e-01, 4.07040320e-01, 4.95063541e-01, 8.90260975e-01],
       [8.82027302e-01, 2.78967882e-02, 2.39068687e-01, 4.46858767e-02],
       [8.13723232e-01, 9.87639834e-01, 6.66882718e-01, 6.64016486e-01],
       [9.19995682e-01, 5.23649212e-01, 8.96383092e-01, 6.22063280e-01],
       [2.19513432e-01, 7.80483174e-01, 9.53436219e-01, 5.10306848e-01],
       [1.43795633e-01, 8.91683689e-01, 5.25485050e-01, 9.60187285e-01],
       [2.05349191e-01, 6.37586719e-01, 4.76678564e-02, 7.04267074e-01],
       [2.13060300e-01, 1.51524944e-01, 8.80732108e

In [85]:
np.random.randint(4,50)#it generates random number between 4 to 50

41

In [86]:
np.random.rand(4,5)

array([[0.10974913, 0.23116453, 0.30538306, 0.11175631, 0.58864769],
       [0.95602549, 0.84374031, 0.88745463, 0.71903339, 0.13457772],
       [0.87666167, 0.40753562, 0.65969482, 0.25505846, 0.03957066],
       [0.10127897, 0.86658425, 0.63180709, 0.12393531, 0.0967186 ]])

In [87]:
pd.DataFrame(np.random.rand(4,5))

0         1         2         3         4
0  0.701718  0.127628  0.853409  0.323935  0.925357
1  0.548745  0.500354  0.852274  0.624664  0.285870
2  0.558166  0.190534  0.908281  0.736349  0.199154
3  0.364587  0.579001  0.167516  0.723412  0.605200

# how to change the dimension of array

In [89]:
a =np.fromfunction(lambda i,j,z,: i*j*z,(4,3,2),dtype = int)


In [90]:
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [91]:
a.reshape(12,2) #we can take only multiple of both the number is 24

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [92]:
pd.DataFrame(a.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [93]:
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])