In [1]:
import numpy as np
import pandas as pd

In [2]:
l = ['krushna',1,2,3,4]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['krushna', '1', '2', '3', '4'], dtype='<U11')

In [5]:
type(np.array(l)) #nd means n-dimensional

numpy.ndarray

In [6]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [7]:
a1= np.array([3,4,5,6,7.0])

In [8]:
a = np.array([[1,2],[3,45]])

In [9]:
np.array([[1,2],[3,45,5]])

C:\Users\KRUSHNA\AppData\Local\Temp\ipykernel_17972\984641819.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[3,45,5]])


array([list([1, 2]), list([3, 45, 5])], dtype=object)

In [10]:
a

array([[ 1,  2],
       [ 3, 45]])

In [11]:
a[1][1]

45

In [12]:
a[1]

array([ 3, 45])

In [13]:
a1

array([3., 4., 5., 6., 7.])

In [14]:
a1[1]

4.0

In [15]:
np.array([1,2,3,4],ndmin = 0)

array([1, 2, 3, 4])

In [16]:
np.array([1,2,3,4],ndmin = 2)

array([[1, 2, 3, 4]])

In [17]:
a2 = np.array([1,2,3,4],ndmin = 3)

In [18]:
a2

array([[[1, 2, 3, 4]]])

In [19]:
a2[0]

array([[1, 2, 3, 4]])

In [20]:
a2[0][0]

array([1, 2, 3, 4])

In [21]:
a2[0][0][0]

1

In [22]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [23]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [24]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [25]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [26]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [27]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [28]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [30]:
np.fromfunction(lambda i,j : i*j,(4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [31]:
np.mat(np.fromfunction(lambda i,j : i*j,(4,4),dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

# NOTE : matrix is a subclass of array

In [32]:
np.fromfunction(lambda i,j,z : i*j*z,(3,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [33]:
np.mat(np.fromfunction(lambda i,j,z : i*j*z,(3,3,2),dtype = int)) # matrix doesn't shows three dimensional array

ValueError: shape too large to be a matrix.

In [ ]:
np.fromfunction(lambda i,j,z : i*j*z,(5,3,2),dtype = int)

In [ ]:
np.fromfunction(lambda i,j,z,p : i*j*z*p,(4,3,2,2),dtype = int)

In [ ]:
a =np.fromfunction(lambda i,j,z,: i*j*z,(4,3,2),dtype = int)
a

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
a

In [ ]:
pd.DataFrame(a)

In [ ]:
a1 =np.fromfunction(lambda i,j,: i*j,(4,3),dtype = int)
a1

In [ ]:
pd.DataFrame(a1)

In [ ]:
a2 =np.fromfunction(lambda i,j,: i*j,(400,400),dtype = int)
a2

In [ ]:
pd.DataFrame(a2)

In [ ]:
np.random.rand(100,4)

In [ ]:
np.random.randint(4,50)#it generates random number between 4 to 50

In [ ]:
np.random.rand(4,5)

In [ ]:
pd.DataFrame(np.random.rand(4,5))

# how to change the dimension of array

In [34]:
a =np.fromfunction(lambda i,j,z,: i*j*z,(4,3,2),dtype = int)


In [35]:
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [36]:
a.reshape(12,2) #we can take only multiple of both the number is 24

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [37]:
pd.DataFrame(a.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [38]:
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [39]:
a.reshape(4,-1) #negative number means it takes the multiple of first number and there answer eqaul to 24

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [41]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [42]:
list(range(4,10,2))

[4, 6, 8]

In [43]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [46]:
a1 = np.arange(4,10,.2)

In [47]:
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [48]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [49]:
arr = np.random.rand(4,5)

In [50]:
arr

array([[0.78479168, 0.47729426, 0.18398237, 0.65370928, 0.15520022],
       [0.52810497, 0.84519881, 0.20653849, 0.63290648, 0.54480151],
       [0.65523507, 0.50385617, 0.5274048 , 0.64501223, 0.95259274],
       [0.85238807, 0.57271291, 0.45083696, 0.78891779, 0.10852199]])

In [51]:
arr > .5

array([[ True, False, False,  True, False],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False]])

In [52]:
arr[arr > .5]

array([0.78479168, 0.65370928, 0.52810497, 0.84519881, 0.63290648,
       0.54480151, 0.65523507, 0.50385617, 0.5274048 , 0.64501223,
       0.95259274, 0.85238807, 0.57271291, 0.78891779])

In [55]:
arr

array([[0.78479168, 0.47729426, 0.18398237, 0.65370928, 0.15520022],
       [0.52810497, 0.84519881, 0.20653849, 0.63290648, 0.54480151],
       [0.65523507, 0.50385617, 0.5274048 , 0.64501223, 0.95259274],
       [0.85238807, 0.57271291, 0.45083696, 0.78891779, 0.10852199]])

In [54]:
arr[[1,2],[2]]

array([0.20653849, 0.5274048 ])

In [57]:
df = pd.DataFrame(arr)

In [59]:
df.iloc[[1,2],[2]]

2
1  0.206538
2  0.527405

In [61]:
arr

array([[0.78479168, 0.47729426, 0.18398237, 0.65370928, 0.15520022],
       [0.52810497, 0.84519881, 0.20653849, 0.63290648, 0.54480151],
       [0.65523507, 0.50385617, 0.5274048 , 0.64501223, 0.95259274],
       [0.85238807, 0.57271291, 0.45083696, 0.78891779, 0.10852199]])

In [62]:
arr = np.random.rand(8,5)

In [63]:
arr

array([[0.24154336, 0.49481973, 0.73047469, 0.95146364, 0.72981548],
       [0.77203054, 0.6296434 , 0.73593425, 0.83940065, 0.02156243],
       [0.73109787, 0.97847239, 0.79536355, 0.67258613, 0.93439864],
       [0.70182111, 0.14908865, 0.85223267, 0.61446061, 0.50423827],
       [0.1117452 , 0.54819543, 0.0276659 , 0.91596412, 0.69851429],
       [0.44575721, 0.50827782, 0.63273627, 0.0082854 , 0.74040504],
       [0.16151633, 0.72195519, 0.07442053, 0.52464813, 0.11502347],
       [0.53414294, 0.75214224, 0.42736282, 0.6574568 , 0.64877266]])

In [64]:
arr[1:8 , 0:3]

array([[0.77203054, 0.6296434 , 0.73593425],
       [0.73109787, 0.97847239, 0.79536355],
       [0.70182111, 0.14908865, 0.85223267],
       [0.1117452 , 0.54819543, 0.0276659 ],
       [0.44575721, 0.50827782, 0.63273627],
       [0.16151633, 0.72195519, 0.07442053],
       [0.53414294, 0.75214224, 0.42736282]])

In [66]:
a2 = arr[1:8 , [0,1,2]]

In [67]:
a2

array([[0.77203054, 0.6296434 , 0.73593425],
       [0.73109787, 0.97847239, 0.79536355],
       [0.70182111, 0.14908865, 0.85223267],
       [0.1117452 , 0.54819543, 0.0276659 ],
       [0.44575721, 0.50827782, 0.63273627],
       [0.16151633, 0.72195519, 0.07442053],
       [0.53414294, 0.75214224, 0.42736282]])

In [68]:
a2[0][0] = 43432

In [69]:
a2

array([[4.34320000e+04, 6.29643399e-01, 7.35934254e-01],
       [7.31097874e-01, 9.78472387e-01, 7.95363546e-01],
       [7.01821109e-01, 1.49088653e-01, 8.52232674e-01],
       [1.11745199e-01, 5.48195430e-01, 2.76659004e-02],
       [4.45757206e-01, 5.08277817e-01, 6.32736275e-01],
       [1.61516328e-01, 7.21955190e-01, 7.44205278e-02],
       [5.34142939e-01, 7.52142239e-01, 4.27362817e-01]])

In [75]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [76]:
a

array([[1, 2],
       [3, 4]])

In [77]:
b

array([[2, 3],
       [4, 5]])

In [78]:
a*b

array([[ 2,  6],
       [12, 20]])

In [81]:
a@b #--> @ represnts the symbol for matrix multiplication

array([[10, 13],
       [22, 29]])

In [82]:
m = a@b

In [83]:
m

array([[10, 13],
       [22, 29]])

In [84]:
m/0

C:\Users\KRUSHNA\AppData\Local\Temp\ipykernel_17972\3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])