In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,56]

In [3]:
np.asarray(l)

array([ 1,  2,  3,  4, 56])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [16]:
np.empty((5,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.67293351e-307],
       [1.89144519e-307, 1.42419938e-306, 7.56603881e-307,
        7.56600486e-307],
       [1.02360867e-306, 1.78022342e-306, 6.23058028e-307,
        1.06811422e-306],
       [9.45699680e-308, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        0.00000000e+000]])

In [13]:
np.empty((5,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [22]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [23]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [24]:
np.linspace(2,6,10,endpoint = False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [26]:
np.linspace(2,6,10,endpoint = False,retstep = True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [27]:
np.linspace(2,6,100,endpoint = False,retstep = True)

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [28]:
np.logspace(2,4,10,base =2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [29]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [33]:
a = np.arange(16).reshape(4,4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
a.max()

15

In [37]:
a = np.arange(4,20).reshape(4,4)

In [38]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
a.max()

19

In [42]:
a = np.arange(4,40).reshape(3,6,2)

In [43]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [44]:
a.max()

39

In [45]:
a.max(axis = 1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [46]:
a = np.arange(4,40).reshape(6,6)

In [60]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [51]:
a.max(axis = 0)

array([34, 35, 36, 37, 38, 39])

In [50]:
a.max(axis = 1)

array([ 9, 15, 21, 27, 33, 39])

In [52]:
10 + a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [53]:
a/0

C:\Users\KRUSHNA\AppData\Local\Temp\ipykernel_19180\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [54]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [55]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [69]:
b = np.array([2,3,1,2,3,2])


In [70]:
b = b.reshape(1,-1)

In [71]:
b

array([[2, 3, 1, 2, 3, 2]])

In [72]:
b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [76]:
b.T + a

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [64]:
a 

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [65]:
a + b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [66]:
b.T

array([2, 3, 1, 2, 3, 2])

In [68]:
a + b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [78]:
b.reshape(1,-1)

array([[2, 3, 1, 2, 3, 2]])

In [79]:
b.reshape(-2321,1)

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [80]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [81]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [82]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [83]:
x = np.array([1,2,3])

In [84]:
y = x # This is shallow copy

In [85]:
y

array([1, 2, 3])

In [86]:
z = np.copy(x) # This is a deep copy 

In [87]:
z

array([1, 2, 3])

In [89]:
x[0] = 100

In [90]:
y

array([100,   2,   3])

In [91]:
z

array([1, 2, 3])

# NOTE : id represents the memory address

In [92]:
id(z) #id is a location

2746661227760

In [93]:
id(x)

2746661227856

In [95]:
id(y)

2746661227856

In [98]:
x

array([100,   2,   3])

In [99]:
id(x[0])

2746659635024

In [100]:
y

array([100,   2,   3])

In [102]:
id(y[0])

2746659633488

In [103]:
id(z[0])

2746659633360

In [111]:
su = np.array([367,245])

In [112]:
df = su

In [113]:
id(su)

2746660813104

In [114]:
id(df)

2746660813104

In [117]:
id(su[0])

2746659625616

In [118]:
id(df[0])

2746659633360

In [119]:
id(su[1])

2746659627056

In [120]:
id(df[1])

2746659633456

In [121]:
id(su[1]) == id(df[1])

True

In [122]:
id(su[1]) == id(df[0])

True

In [123]:
id(su) == id(df)

True

In [124]:
xt = np.array([34,67,89])

In [126]:
id(xt[0]) == id(su[0])

True

In [135]:
c = np.array(["krushna"])

In [138]:
c

array('krushna', dtype='<U7')

In [128]:
d = "teli"

In [139]:
id(c) == id(d)

False

In [140]:
id(c) == id(xt)

False